# Generated by Django 5.0.1 on 2024-01-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_order_customer_order_status'),
        ('seller', '0003_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_ordered_sellerID',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_ordered_sellerID',
            field=models.ManyToManyField(to='seller.seller', verbose_name='OrderedFulFillOrderedID'),
        ),
    ]
