# Generated by Django 5.0.1 on 2024-01-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_order_customer_ordered_sellerid_and_more'),
        ('seller', '0003_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_ordered_sellerID',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_ordered_sellerID',
            field=models.ManyToManyField(to='seller.seller', verbose_name='OrderedFulFillOrderedID'),
        ),
    ]
