# Generated by Django 5.0.1 on 2024-01-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_order_customer_ordered_sellerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_ordered_sellerID',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_order_status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SHIPPED', 'Order Shipped'), ('RETURN', 'Order Returned'), ('CANCEL', 'Order Cancelled')], default='ORDERED', max_length=150),
        ),
    ]
