# Generated by Django 5.0.1 on 2024-01-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_order_customer_ordered_sellerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
    ]
