# Generated by Django 5.0.1 on 2024-01-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customer_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.ManyToManyField(blank=True, null=True, to='customer.address'),
        ),
    ]
