# Generated by Django 5.0.1 on 2024-01-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_pwd',
            field=models.CharField(max_length=250),
        ),
    ]
