# Generated by Django 5.0.1 on 2024-01-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
