# Generated by Django 5.0.1 on 2024-01-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0016_alter_customer_is_authenticated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="is_authenticated",
            field=models.BooleanField(default=True),
        ),
    ]
