# Generated by Django 5.0.1 on 2024-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('category_products', models.ManyToManyField(blank=True, null=True, to='seller.product', verbose_name='listOfProd')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(to='seller.productcategory', verbose_name='listOfCat'),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(blank=True, max_length=150)),
                ('seller_user_id', models.CharField(max_length=50)),
                ('seller_pwd', models.CharField(max_length=250)),
                ('seller_city', models.CharField(max_length=50)),
                ('seller_mobile', models.CharField(max_length=10)),
                ('seller_products', models.ManyToManyField(blank=True, null=True, to='seller.product', verbose_name='listOfSellerProd')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='products_sellers',
            field=models.ManyToManyField(to='seller.seller'),
        ),
    ]
