# Generated by Django 5.0.1 on 2024-01-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(to='seller.productcategory', verbose_name='listOfCat'),
        ),
    ]
