# Generated by Django 5.0.1 on 2024-02-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0006_alter_product_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_quantity",
            field=models.IntegerField(default=1),
        ),
    ]
