# Generated by Django 5.0.1 on 2024-01-24 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0017_alter_customer_is_authenticated"),
        ("customer_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserAuthToken",
            new_name="UserAuthTokenModel",
        ),
    ]
