# Generated by Django 5.0.1 on 2024-01-30 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_api", "0002_rename_userauthtoken_userauthtokenmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userauthtokenmodel",
            options={},
        ),
    ]
